### ISSUE TITLE
Events spanning more than 1 day

### ISSUE THREAD

**Issue by richardmayo** [ljmerza/calendar-card#17]
Hi

Ive noticed that all day events that span more than 1 day, only show on the day that it starts. There is no way to identify which days those events end.

Would it be possible to either have the event replicate on each day its active, or somehow in the time section, have it indicate the date it finishes if the date is not the same date the event started on.

Awesome card, loving it!

Thanks

**Comment by ljmerza** [comment]
Add support for multi-day events in version 3.9.0 via the `showMultiDay` option. Let me know if it works so I can close this. Thanks.

**Comment by ghost** [comment]
cant seem to get it working, is it `true` or `false` that should make a multiday appointment appear on every day?

**Comment by ljmerza** [comment]
it should be set to `true` on the latest version i just released. It'll look like this

![image](https://user-images.githubusercontent.com/4085765/56086856-44a95c80-5e2d-11e9-964c-453c784846e8.png)

If you can't get it working give me the exact start and end date and ill create a test event to see if I can reproduce.

**Comment by ljmerza** [comment]
I did see a small issue with the multiday stuff so I've fixed that and updated to v3.9.1 let me know if that fixes it. Thanks.

**Comment by michaeldvinci** [comment]
I am not seeing multi-day events show up with showMultiDay: true. tried with false as well and that doesn't seem to work either!

**Comment by ljmerza** [comment]
What type of events are these? Are they from Google calendar? What's the
start and end dates?

**Comment by michaeldvinci** [comment]
They are all day events starting 4/15 and ending on 4/16 created in google calendar

**Comment by ljmerza** [comment]
All day events aren't multiday they're just 'all day'. They end at 00:00:00
the next day.

**Comment by michaeldvinci** [comment]
Sorry I must have misspoken, as this is a multi-day all day event. I only see it show up on the first day when enabled in the calendar-card

```
- entities:
    - calendar.bills
    - calendar.events
    - calendar.gwu
    - calendar.gym_time
    - calendar.http_followshows_com_ical_9oejn9ol
    - calendar.killshot_burgundy
    - calendar.michaeldvinci_gmail_com
    - calendar.miro
    - calendar.people
    - calendar.potential_trips
    - calendar.pre_order
    - calendar.things_to_remember
    - calendar.work_solers
  numberOfDays: 2
  progressBar: true
  showMultiDay: true
  timeFormat: 'hh:mm a'
  title: false
  type: 'custom:calendar-card'
```

![image](https://user-images.githubusercontent.com/8780953/56174464-9afad480-5fc0-11e9-82c4-b2a7a82453bd.png)

![image](https://user-images.githubusercontent.com/8780953/56174502-c2ea3800-5fc0-11e9-83ad-7f15ab41a9b9.png)
