### ISSUE TITLE
Card showing yesterday's events

### ISSUE THREAD

**Issue by michaeldvinci** [ljmerza/calendar-card#23]
The image below was taken today on 4/15, and as you can see it's showing the events from Sunday 4/14 which shouldn't be there. could this be an issue with my system time perhaps [even though lovelace is showing the right datetime in the top right corner]?

```
- entities:
    - calendar.bills
    - calendar.events
    - calendar.gwu
    - calendar.gym_time
    - calendar.http_followshows_com_ical_9oejn9ol
    - calendar.killshot_burgundy
    - calendar.michaeldvinci_gmail_com
    - calendar.miro
    - calendar.people
    - calendar.potential_trips
    - calendar.pre_order
    - calendar.things_to_remember
    - calendar.work_solers
  numberOfDays: 2
  progressBar: true
  showMultiDay: true
  timeFormat: 'hh:mm a'
  title: false
  type: 'custom:calendar-card'
```

![image](https://user-images.githubusercontent.com/8780953/56173992-3f2f4c00-5fbe-11e9-8913-b1d3019ff47d.png)
