### ISSUE TITLE
vobject.base.ParseError: At line 33: DURATION must have a single duration string.

### ISSUE THREAD

**Issue by hendrikma** [ljmerza/calendar-card#50]
Unfortunately i cannot get your plugin to work with my calendar :/

**I got this error in homeassistant:**

`Traceback** (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 40, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 73, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 231, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 128, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 193, in get
    request.app["hass"], start_date, end_date
  File "/usr/src/homeassistant/homeassistant/components/caldav/calendar.py", line 142, in async_get_events
    return await self.data.async_get_events(hass, start_date, end_date)
  File "/usr/src/homeassistant/homeassistant/components/caldav/calendar.py", line 174, in async_get_events
    vevent = event.instance.vevent
  File "/usr/local/lib/python3.7/site-packages/caldav/objects.py", line 995, in _get_vobject_instance
    self._vobject_instance = vobject.readOne(to_unicode(self._data))
  File "/usr/local/lib/python3.7/site-packages/vobject/base.py", line 1156, in readOne
    allowQP))
  File "/usr/local/lib/python3.7/site-packages/vobject/base.py", line 1128, in readComponents
    component.transformChildrenToNative()
  File "/usr/local/lib/python3.7/site-packages/vobject/base.py", line 674, in transformChildrenToNative
    child.transformChildrenToNative()
  File "/usr/local/lib/python3.7/site-packages/vobject/base.py", line 673, in transformChildrenToNative
    child = child.transformToNative()
  File "/usr/local/lib/python3.7/site-packages/vobject/base.py", line 185, in transformToNative
    return self.behavior.transformToNative(self)
  File "/usr/local/lib/python3.7/site-packages/vobject/icalendar.py", line 1454, in transformToNative
    raise ParseError("DURATION must have a single duration string.")
vobject.base.ParseError: At line 33: DURATION must have a single duration string.`

That's my configuration:

```
title: My Calendar
numberOfDays: '3'
timeFormat: 'HH:mm'
dateTopFormat: DD
dateBottomFormat: ddd
hideTime: false
progressBar: true
showLocation: true
showLocationIcon: true
showMultiDay: true
startFromToday: false
showEventOrigin: false
hideHeader: false
type: 'custom:calendar-card'
entities:
  - entity: calendar.abfallkalender
    name: calendar.abfallkalender
```
