### ISSUE TITLE
iCloud 'All Day' events not showing

### ISSUE THREAD

**Issue by PierreScerri** [ljmerza/calendar-card#63]
Hi

I have both Google calendars and iCloud CALDAV calendars setup.  

All Day events from the Caldav calendars are not showing.

Is this expected behaviour?

Thank you.

**Comment by ljmerza** [comment]
whats your config for this card?

**Comment by PierreScerri** [comment]
This is my config:
```
title: Coming Up
numberOfDays: '10'
timeFormat: 'HH:mma'
dateTopFormat: DD
dateBottomFormat: ddd
hideTime: false
progressBar: true
showLocation: true
showLocationIcon: true
startFromToday: true
hidePastEvents: true
showMultiDay: true
eventsLimit: '99'
showEventOrigin: true
hideHeader: false
highlightToday: true
ignoreEventsExpression: ''
ignoreEventsByLocationExpression: ''
entities:
  - entity: calendar.pierre
    name: Pierre
  - entity: calendar.emily
    name: Emily
  - entity: calendar.scerri_nicole
    name: Nicole
  - entity: calendar.holiday
    name: Holiday
  - entity: calendar.meter
    name: Meter
  - entity: calendar.payments
    name: Payments
  - entity: calendar.terry
    name: Terry
  - entity: calendar.finance
    name: Finance
  - entity: calendar.anniversary
    name: Anniversary
  - entity: calendar.medical
    name: Medical
  - entity: calendar.home
    name: Home
  - entity: calendar.reminders
    name: Reminders
type: 'custom:calendar-card'

```

The Mail App on MacOS also has a calendar for Birthdays that picks up the data from Contacts.  These are also all-day events and not shown.  The 'Birthdays' calendar is not seen by the card. Tried adding it manually but does not come up.

The first 3 calendars in the list are gmail calendars.  The rest are iOS calendars.
