### ISSUE TITLE
showEventOrigin not working

### ISSUE THREAD

**Issue by pdcemulator** [ljmerza/calendar-card#75]
Hi,
this is my calendar config:
`  - type: custom:calendar-card
    title: "Kalender"
    entities:
    - calendar.cal_a
    - calendar.cal_b
    timeFormat: HH:mm
    showEventOrigin: true
    showLocation: true
    highlightToday: true
    hidePastEvents: true`

I would expect to see the calendar name for each event, but it does not show up.
Data source is a private Nextcloud instance.
version 3.103.1

**Comment by ljmerza** [comment]
The data structure might be different since it's coming from a Nextcloud instance. Can you tell me the event object property for the event origin? Or paste a whole event object here stripping any personal info you want

**Comment by pdcemulator** [comment]
Found this in Developer Tools / States

```
message: example
all_day: false
start_time: 2020-01-13 17:30:00
end_time: 2020-01-13 18:30:00
location: null
description: [example]

offset_reached: false
friendly_name: cal 1
```

**Comment by ljmerza** [comment]
ok doesnt look like events give back origin. what does the calendar editor show? it should fall back to the sensor name if events dont give anything

![image](https://user-images.githubusercontent.com/4085765/72302322-a35b6b00-3637-11ea-96cf-6f6f44c9cb31.png)


also can you paste your yaml here?

**Comment by pdcemulator** [comment]
view:
```
    - type: custom:calendar-card
      title: "Kalender"
      entities:
      - calendar.cal_1
      - calendar.cal_2
      timeFormat: HH:mm
      showEventOrigin: true
      showLocation: true
      highlightToday: true
      hidePastEvents: true
      eventsLimit: 8
```

calendar:
```
calendar:
  - platform: caldav
    username: !secret caldav_username
    password: !secret caldav_password
    url: !secret caldav_url
```

Entity: calendar.cal_1
friendly_name: Cal 1
Entity: calendar.cal_2
friendly_name: Cal 2

I think it would be the best solution to show the friendly name
