### ISSUE TITLE
card-modder support

### ISSUE THREAD

**Issue by VirtualL** [ljmerza/calendar-card#9]
Hi, I am really like the new change, working perfectly on RTL language, (before this change I was made changes in the JS file to add Hebrew Language and some adjustment to RTL ), So it's great now.

All My HA setup use the card-modder (https://github.com/thomasloven/lovelace-card-modder)
and your new calendar implementation doesn't work with this custom-UI.

There is an option to made it work? Thank you

**Comment by ljmerza** [comment]
I was able to use card modder just fine. Is there a particular setting that's not working?

![image](https://user-images.githubusercontent.com/4085765/52718518-a6eef980-2f71-11e9-93d4-a302f0bd47f9.png)

**Comment by VirtualL** [comment]
Strange, 
when I try this code: 
```
          - type: custom:card-modder
            style:
              border-radius: 20px
              background-color: rgba(255,0,0,0.3)
              background-image: url("/local/lovelace/background/cardbackk.png")
              background-repeat: no-repeat
              background-size: 100% 68px
              border: solid 1px rgba(100,100,100,0.3)
              box-shadow: 3px 3px rgba(0,0,0,0.4)
              overflow: hidden
            card:
              type: "custom:calendar-card"
              title: "לוח שנה"
              numberOfDays: 14
              entities:
                - calendar.work
                - calendar.icloudhome
```
noting happend, but if I will try this style it will work:
```
  style:
    --paper-card-background-color: rgba(0, 100, 0, 0.2)
    --paper-item-icon-color: white
    border-radius: 5px
    color: rgb(0, 0, 100)
```

any idea why? this style working well all over my config.

**Comment by ljmerza** [comment]
I'm not really sure. I looked through the card modder code and couldnt see a reason why it doesnt work. The author of the card modder might now more as he's familiar with my calendar card

**Comment by jimz011** [comment]
> 
> 
> Strange,
> when I try this code:
> 
> ```
>           - type: custom:card-modder
>             style:
>               border-radius: 20px
>               background-color: rgba(255,0,0,0.3)
>               background-image: url("/local/lovelace/background/cardbackk.png")
>               background-repeat: no-repeat
>               background-size: 100% 68px
>               border: solid 1px rgba(100,100,100,0.3)
>               box-shadow: 3px 3px rgba(0,0,0,0.4)
>               overflow: hidden
>             card:
>               type: "custom:calendar-card"
>               title: "לוח שנה"
>               numberOfDays: 14
>               entities:
>                 - calendar.work
>                 - calendar.icloudhome
> ```
> 
> noting happend, but if I will try this style it will work:
> 
> ```
>   style:
>     --paper-card-background-color: rgba(0, 100, 0, 0.2)
>     --paper-item-icon-color: white
>     border-radius: 5px
>     color: rgb(0, 0, 100)
> ```
> 
> any idea why? this style working well all over my config.



This is an old thread, but still open, I figured I would look at the code,
the following line though caught my attention:

`border: solid 1px rgba(100,100,100,0.3)`

Doesn't it take more parameters to do this? something like:

`border-style: solid`
`border-color: '#FFFFFF'`
`border-width: 1px`

**Comment by ljmerza** [comment]
its `border: 1px solid rgba(100,100,100,0.3)` now that i think about it

**Comment by kugan49** [comment]
`border: 1px solid rgba(100,100,100,0.3)` or `border: solid 1px rgba(100,100,100,0.3)` have same result on chrome

**Comment by VirtualL** [comment]
I made it work 2 months ago, just forget this topic...

My working config : 

```
          - type: custom:card-modder
            card:
              type: "custom:calendar-card"
              progressBar: true
              entities:
                - calendar.work
                - calendar.icloudhome
            style:
              border: 1px solid rgba(100,100,100,0.3)
              border-radius: 20px
              --paper-card-background-color: rgba(50, 50, 50, 0.3)
              box-shadow: 3px 3px rgba(0,0,0,0.4)
```
Its been working great, til the new relese https://github.com/ljmerza/calendar-card/releases/tag/3.8.0

> Added loading spinner when loading calendar

now the card modder loaded before OK, but after the loading of calender-card - it's going back to be without card-modder.
![A](https://user-images.githubusercontent.com/10164935/56075200-5d7f2700-5dc7-11e9-9ad3-3051ec39d8dd.gif)


Before v3.8.0 its been like this:
<img width="309" alt="LovelaceUI_01" src="https://user-images.githubusercontent.com/10164935/56075221-b64ebf80-5dc7-11e9-8078-2e002009fc49.png">
